CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Clients" (
    "ClientId" text NOT NULL,
    "ClientSecret" text NOT NULL,
    "ClientName" text NOT NULL,
    CONSTRAINT "PK_Clients" PRIMARY KEY ("ClientId")
);

CREATE TABLE "CodeValidators" (
    "Id" uuid NOT NULL,
    "VerificationCode" character varying(6) NOT NULL,
    "Status" text NOT NULL,
    "VerificationType" text NOT NULL,
    "Target" character varying(256) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CodeValidators" PRIMARY KEY ("Id")
);

CREATE TABLE "DataProtectionKeys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FriendlyName" text,
    "Xml" text,
    CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" text NOT NULL,
    "Username" character varying(50) NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50),
    "Birthdate" date,
    "Gender" character varying(10),
    "Email" character varying(100) NOT NULL,
    "EmailVerificationHash" text,
    "EmailVerified" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "ClientGrantTypes" (
    "ClientGrantTypeId" text NOT NULL,
    "ClientId" text NOT NULL,
    "GrantType" text NOT NULL,
    CONSTRAINT "PK_ClientGrantTypes" PRIMARY KEY ("ClientGrantTypeId"),
    CONSTRAINT "FK_ClientGrantTypes_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("ClientId") ON DELETE CASCADE
);

CREATE TABLE "ClientRedirectUris" (
    "ClientRedirectUriId" text NOT NULL,
    "ClientId" text NOT NULL,
    "RedirectUri" text NOT NULL,
    CONSTRAINT "PK_ClientRedirectUris" PRIMARY KEY ("ClientRedirectUriId"),
    CONSTRAINT "FK_ClientRedirectUris_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("ClientId") ON DELETE CASCADE
);

CREATE TABLE "ClientScopes" (
    "ClientScopeId" text NOT NULL,
    "ClientId" text NOT NULL,
    "Scope" text NOT NULL,
    CONSTRAINT "PK_ClientScopes" PRIMARY KEY ("ClientScopeId"),
    CONSTRAINT "FK_ClientScopes_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("ClientId") ON DELETE CASCADE
);

CREATE TABLE "AuthorizationCodes" (
    "AuthorizationCodeId" text NOT NULL,
    "Code" text NOT NULL,
    "ClientId" text NOT NULL,
    "UserId" text NOT NULL,
    "RedirectUri" text NOT NULL,
    "Scopes" text NOT NULL,
    "CodeChallenge" text NOT NULL,
    "CodeChallengeMethod" text NOT NULL,
    "Expiry" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuthorizationCodes" PRIMARY KEY ("AuthorizationCodeId"),
    CONSTRAINT "FK_AuthorizationCodes_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("ClientId") ON DELETE CASCADE,
    CONSTRAINT "FK_AuthorizationCodes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Tokens" (
    "TokenId" text NOT NULL,
    "TokenType" text NOT NULL,
    "Value" text NOT NULL,
    "ClientId" text NOT NULL,
    "UserId" text NOT NULL,
    "Expiry" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Tokens" PRIMARY KEY ("TokenId"),
    CONSTRAINT "FK_Tokens_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("ClientId") ON DELETE CASCADE,
    CONSTRAINT "FK_Tokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserClaims" (
    "Id" text NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" character varying(50) NOT NULL,
    "ClaimValue" character varying(50) NOT NULL,
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserRoles" (
    "Id" text NOT NULL,
    "UserId" text NOT NULL,
    "Role" character varying(50) NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AuthorizationCodes_ClientId" ON "AuthorizationCodes" ("ClientId");

CREATE INDEX "IX_AuthorizationCodes_UserId" ON "AuthorizationCodes" ("UserId");

CREATE INDEX "IX_ClientGrantTypes_ClientId" ON "ClientGrantTypes" ("ClientId");

CREATE INDEX "IX_ClientRedirectUris_ClientId" ON "ClientRedirectUris" ("ClientId");

CREATE INDEX "IX_ClientScopes_ClientId" ON "ClientScopes" ("ClientId");

CREATE UNIQUE INDEX "IX_CodeValidators_Target_Code" ON "CodeValidators" ("Target", "VerificationCode");

CREATE INDEX "IX_Tokens_ClientId" ON "Tokens" ("ClientId");

CREATE INDEX "IX_Tokens_UserId" ON "Tokens" ("UserId");

CREATE INDEX "IX_UserClaims_UserId" ON "UserClaims" ("UserId");

CREATE INDEX "IX_UserRoles_UserId" ON "UserRoles" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240722055907_InitialCreate', '8.0.7');

COMMIT;

