trigger:
  batch: true
  branches:
    include:
      - develop
      - master
      - release/*
  paths:
    include:
      - src
    exclude:
      - docs


variables:
  vmImageName: 'ubuntu-latest'

extends:
  template: base-pipeline.yml
  parameters:
    nodeVersion: '20.x'
    app: 'iam-server'  # Replace with your actual Angular app name
    angularAppPath: 'src/aiglusoft.iam.client'  # Replace with the path to your Angular app
    projectPath: 'src/Aiglusoft.IAM.Server/*.csproj'  # Replace with the path to your .NET project or solution
    dockerfilePath: 'src/Aiglusoft.IAM.Server/Dockerfile'  # Replace with the path to your Dockerfile
    dockerRegistryServiceConnection: 'dockerhub'  # Replace with your Docker registry service connection
    dockerRepository: 'aiglusoft'  # Replace with your Docker repository
    angularArtifactName: 'iam-wwwroot'  # Optional: replace with your desired artifact name, or leave it to use the default
    buildConfiguration: 'Release'  # Optional: replace with your build configuration
    coberturaOutputFormat: '/p:CoverletOutputFormat=cobertura'  # Optional: replace with your Cobertura output format
    # unitTestPath: 'path/to/unit/tests/*.csproj'  # Optional: replace with the path to your unit tests
    # e2eTestPath: 'path/to/e2e/tests/*.csproj'  # Optional: replace with the path to your end-to-end tests
